import { Table, TableContainer, Paper, TableBody, TableHead, TableRow, TableCell, Tooltip, IconButton } from "@mui/material"
import DeleteIcon from '@mui/icons-material/Delete';

//mockaroo.com
const tableData = [{
    "id": 1,
    "first_name": "Simone",
    "last_name": "Pryce",
    "email": "spryce0@prweb.com",
    "gender": "Agender",
    "ip_address": "166.27.35.93"
  }, {
    "id": 2,
    "first_name": "Bev",
    "last_name": "Featherstonhalgh",
    "email": "bfeatherstonhalgh1@virginia.edu",
    "gender": "Female",
    "ip_address": "63.93.186.4"
  }, {
    "id": 3,
    "first_name": "Zorana",
    "last_name": "Dickman",
    "email": "zdickman2@alibaba.com",
    "gender": "Female",
    "ip_address": "5.138.37.235"
  }, {
    "id": 4,
    "first_name": "Edithe",
    "last_name": "Tuther",
    "email": "etuther3@businessweek.com",
    "gender": "Genderqueer",
    "ip_address": "200.222.168.172"
  }, {
    "id": 5,
    "first_name": "Flossy",
    "last_name": "Orniz",
    "email": "forniz4@sphinn.com",
    "gender": "Female",
    "ip_address": "184.117.97.15"
  }, {
    "id": 6,
    "first_name": "Alphonso",
    "last_name": "Howcroft",
    "email": "ahowcroft5@spiegel.de",
    "gender": "Male",
    "ip_address": "168.130.162.39"
  }, {
    "id": 7,
    "first_name": "Elle",
    "last_name": "Castaignet",
    "email": "ecastaignet6@weather.com",
    "gender": "Bigender",
    "ip_address": "198.21.90.253"
  }, {
    "id": 8,
    "first_name": "Erv",
    "last_name": "Ciepluch",
    "email": "eciepluch7@businessinsider.com",
    "gender": "Male",
    "ip_address": "113.19.199.250"
  }, {
    "id": 9,
    "first_name": "Granville",
    "last_name": "Barabich",
    "email": "gbarabich8@behance.net",
    "gender": "Male",
    "ip_address": "174.14.165.149"
  }, {
    "id": 10,
    "first_name": "Augusta",
    "last_name": "Koubek",
    "email": "akoubek9@networksolutions.com",
    "gender": "Female",
    "ip_address": "177.149.175.124"
  }, {
    "id": 11,
    "first_name": "Carine",
    "last_name": "Strong",
    "email": "cstronga@devhub.com",
    "gender": "Female",
    "ip_address": "138.206.137.2"
  }, {
    "id": 12,
    "first_name": "Thaddeus",
    "last_name": "Charrisson",
    "email": "tcharrissonb@miitbeian.gov.cn",
    "gender": "Male",
    "ip_address": "183.90.21.109"
  }, {
    "id": 13,
    "first_name": "Averill",
    "last_name": "Sailor",
    "email": "asailorc@geocities.jp",
    "gender": "Male",
    "ip_address": "70.175.138.160"
  }, {
    "id": 14,
    "first_name": "Lenee",
    "last_name": "Malloy",
    "email": "lmalloyd@alexa.com",
    "gender": "Female",
    "ip_address": "72.196.72.14"
  }, {
    "id": 15,
    "first_name": "Jeanna",
    "last_name": "Bene",
    "email": "jbenee@printfriendly.com",
    "gender": "Female",
    "ip_address": "27.121.38.120"
  }, {
    "id": 16,
    "first_name": "Lucias",
    "last_name": "Landsberg",
    "email": "llandsbergf@free.fr",
    "gender": "Male",
    "ip_address": "139.167.102.194"
  }, {
    "id": 17,
    "first_name": "Dallas",
    "last_name": "De Ruggero",
    "email": "dderuggerog@ucoz.com",
    "gender": "Genderqueer",
    "ip_address": "172.62.82.57"
  }, {
    "id": 18,
    "first_name": "Goran",
    "last_name": "Stapforth",
    "email": "gstapforthh@wufoo.com",
    "gender": "Male",
    "ip_address": "50.72.200.137"
  }, {
    "id": 19,
    "first_name": "Delmar",
    "last_name": "Jowsey",
    "email": "djowseyi@cnn.com",
    "gender": "Male",
    "ip_address": "122.114.55.37"
  }, {
    "id": 20,
    "first_name": "Meyer",
    "last_name": "MacGaughie",
    "email": "mmacgaughiej@barnesandnoble.com",
    "gender": "Male",
    "ip_address": "83.52.212.240"
  }, {
    "id": 21,
    "first_name": "Perla",
    "last_name": "Bather",
    "email": "pbatherk@bbc.co.uk",
    "gender": "Female",
    "ip_address": "53.161.3.78"
  }, {
    "id": 22,
    "first_name": "Karine",
    "last_name": "Gamil",
    "email": "kgamill@yahoo.co.jp",
    "gender": "Female",
    "ip_address": "23.131.113.21"
  }, {
    "id": 23,
    "first_name": "Jourdan",
    "last_name": "Easbie",
    "email": "jeasbiem@patch.com",
    "gender": "Female",
    "ip_address": "224.32.101.74"
  }, {
    "id": 24,
    "first_name": "Ilka",
    "last_name": "Kencott",
    "email": "ikencottn@comsenz.com",
    "gender": "Female",
    "ip_address": "151.152.249.203"
  }, {
    "id": 25,
    "first_name": "Kellia",
    "last_name": "Brookson",
    "email": "kbrooksono@uol.com.br",
    "gender": "Female",
    "ip_address": "241.2.164.9"
  }, {
    "id": 26,
    "first_name": "Michel",
    "last_name": "Danett",
    "email": "mdanettp@last.fm",
    "gender": "Female",
    "ip_address": "53.98.18.116"
  }, {
    "id": 27,
    "first_name": "Tuck",
    "last_name": "Gladwish",
    "email": "tgladwishq@ftc.gov",
    "gender": "Male",
    "ip_address": "255.182.161.1"
  }, {
    "id": 28,
    "first_name": "Priscilla",
    "last_name": "Marklow",
    "email": "pmarklowr@macromedia.com",
    "gender": "Genderfluid",
    "ip_address": "212.113.105.52"
  }, {
    "id": 29,
    "first_name": "Celinka",
    "last_name": "Burrage",
    "email": "cburrages@joomla.org",
    "gender": "Female",
    "ip_address": "59.139.23.83"
  }, {
    "id": 30,
    "first_name": "Fonz",
    "last_name": "Espinola",
    "email": "fespinolat@elpais.com",
    "gender": "Male",
    "ip_address": "26.218.200.149"
  }, {
    "id": 31,
    "first_name": "Vickie",
    "last_name": "Haker",
    "email": "vhakeru@people.com.cn",
    "gender": "Female",
    "ip_address": "222.133.75.169"
  }, {
    "id": 32,
    "first_name": "Hanni",
    "last_name": "Bruggen",
    "email": "hbruggenv@yellowpages.com",
    "gender": "Female",
    "ip_address": "90.167.161.187"
  }, {
    "id": 33,
    "first_name": "Audrey",
    "last_name": "Figgen",
    "email": "afiggenw@sitemeter.com",
    "gender": "Female",
    "ip_address": "27.158.74.108"
  }, {
    "id": 34,
    "first_name": "Marlowe",
    "last_name": "Keepe",
    "email": "mkeepex@wiley.com",
    "gender": "Male",
    "ip_address": "62.65.76.34"
  }, {
    "id": 35,
    "first_name": "Natassia",
    "last_name": "Ekins",
    "email": "nekinsy@storify.com",
    "gender": "Female",
    "ip_address": "255.245.142.226"
  }, {
    "id": 36,
    "first_name": "Lily",
    "last_name": "Moehle",
    "email": "lmoehlez@mapquest.com",
    "gender": "Bigender",
    "ip_address": "147.164.30.77"
  }, {
    "id": 37,
    "first_name": "Murry",
    "last_name": "Piddick",
    "email": "mpiddick10@census.gov",
    "gender": "Male",
    "ip_address": "132.135.69.7"
  }, {
    "id": 38,
    "first_name": "Sibeal",
    "last_name": "Hearnshaw",
    "email": "shearnshaw11@free.fr",
    "gender": "Female",
    "ip_address": "250.149.115.12"
  }, {
    "id": 39,
    "first_name": "Fifine",
    "last_name": "Crellim",
    "email": "fcrellim12@squarespace.com",
    "gender": "Female",
    "ip_address": "95.214.164.92"
  }, {
    "id": 40,
    "first_name": "Innis",
    "last_name": "Downgate",
    "email": "idowngate13@homestead.com",
    "gender": "Male",
    "ip_address": "197.211.35.45"
  }, {
    "id": 41,
    "first_name": "Mortimer",
    "last_name": "Rose",
    "email": "mrose14@samsung.com",
    "gender": "Male",
    "ip_address": "230.232.68.198"
  }, {
    "id": 42,
    "first_name": "Heidie",
    "last_name": "Shearmer",
    "email": "hshearmer15@hhs.gov",
    "gender": "Female",
    "ip_address": "185.34.49.222"
  }, {
    "id": 43,
    "first_name": "Danita",
    "last_name": "Pulbrook",
    "email": "dpulbrook16@nbcnews.com",
    "gender": "Female",
    "ip_address": "244.213.35.91"
  }, {
    "id": 44,
    "first_name": "Frederic",
    "last_name": "Demeza",
    "email": "fdemeza17@wp.com",
    "gender": "Male",
    "ip_address": "53.3.82.51"
  }, {
    "id": 45,
    "first_name": "Hamish",
    "last_name": "Flasby",
    "email": "hflasby18@sphinn.com",
    "gender": "Male",
    "ip_address": "191.237.249.137"
  }, {
    "id": 46,
    "first_name": "Trever",
    "last_name": "Macconachy",
    "email": "tmacconachy19@fastcompany.com",
    "gender": "Male",
    "ip_address": "90.202.249.107"
  }, {
    "id": 47,
    "first_name": "Suzanna",
    "last_name": "Aberchirder",
    "email": "saberchirder1a@bbc.co.uk",
    "gender": "Female",
    "ip_address": "200.182.47.8"
  }, {
    "id": 48,
    "first_name": "Billye",
    "last_name": "Stubbin",
    "email": "bstubbin1b@sun.com",
    "gender": "Female",
    "ip_address": "216.24.190.82"
  }, {
    "id": 49,
    "first_name": "Darla",
    "last_name": "Piff",
    "email": "dpiff1c@homestead.com",
    "gender": "Female",
    "ip_address": "13.129.220.6"
  }, {
    "id": 50,
    "first_name": "Garrik",
    "last_name": "Spiaggia",
    "email": "gspiaggia1d@unesco.org",
    "gender": "Male",
    "ip_address": "29.191.71.200"
  }, {
    "id": 51,
    "first_name": "Gill",
    "last_name": "Thiese",
    "email": "gthiese1e@go.com",
    "gender": "Female",
    "ip_address": "149.202.18.229"
  }, {
    "id": 52,
    "first_name": "Warden",
    "last_name": "Grandison",
    "email": "wgrandison1f@reverbnation.com",
    "gender": "Male",
    "ip_address": "39.60.233.23"
  }, {
    "id": 53,
    "first_name": "Moshe",
    "last_name": "Blakeborough",
    "email": "mblakeborough1g@nationalgeographic.com",
    "gender": "Male",
    "ip_address": "88.84.4.251"
  }, {
    "id": 54,
    "first_name": "Celinka",
    "last_name": "Maddrell",
    "email": "cmaddrell1h@va.gov",
    "gender": "Female",
    "ip_address": "39.125.26.175"
  }, {
    "id": 55,
    "first_name": "Emerson",
    "last_name": "Heinert",
    "email": "eheinert1i@jigsy.com",
    "gender": "Male",
    "ip_address": "79.35.14.228"
  }, {
    "id": 56,
    "first_name": "Piotr",
    "last_name": "Arrell",
    "email": "parrell1j@photobucket.com",
    "gender": "Male",
    "ip_address": "32.230.137.35"
  }, {
    "id": 57,
    "first_name": "Staci",
    "last_name": "Thelwll",
    "email": "sthelwll1k@wufoo.com",
    "gender": "Female",
    "ip_address": "252.198.246.64"
  }, {
    "id": 58,
    "first_name": "Prentiss",
    "last_name": "Draayer",
    "email": "pdraayer1l@gnu.org",
    "gender": "Male",
    "ip_address": "42.195.99.101"
  }, {
    "id": 59,
    "first_name": "Gilbertine",
    "last_name": "Espada",
    "email": "gespada1m@wikipedia.org",
    "gender": "Female",
    "ip_address": "116.23.14.25"
  }, {
    "id": 60,
    "first_name": "Lillian",
    "last_name": "Backshell",
    "email": "lbackshell1n@reference.com",
    "gender": "Female",
    "ip_address": "37.9.44.107"
  }, {
    "id": 61,
    "first_name": "Alanson",
    "last_name": "Eyes",
    "email": "aeyes1o@npr.org",
    "gender": "Male",
    "ip_address": "59.63.9.186"
  }, {
    "id": 62,
    "first_name": "Lazare",
    "last_name": "Cahani",
    "email": "lcahani1p@disqus.com",
    "gender": "Male",
    "ip_address": "241.113.41.233"
  }, {
    "id": 63,
    "first_name": "Olivero",
    "last_name": "Rothchild",
    "email": "orothchild1q@blogtalkradio.com",
    "gender": "Male",
    "ip_address": "20.9.59.196"
  }, {
    "id": 64,
    "first_name": "Steve",
    "last_name": "Dillestone",
    "email": "sdillestone1r@independent.co.uk",
    "gender": "Male",
    "ip_address": "233.147.174.189"
  }, {
    "id": 65,
    "first_name": "Chickie",
    "last_name": "Loftie",
    "email": "cloftie1s@dmoz.org",
    "gender": "Male",
    "ip_address": "133.36.163.92"
  }, {
    "id": 66,
    "first_name": "Taddeusz",
    "last_name": "Vasnev",
    "email": "tvasnev1t@baidu.com",
    "gender": "Male",
    "ip_address": "63.141.81.22"
  }, {
    "id": 67,
    "first_name": "Farley",
    "last_name": "Dohrmann",
    "email": "fdohrmann1u@nifty.com",
    "gender": "Male",
    "ip_address": "44.221.238.27"
  }, {
    "id": 68,
    "first_name": "Renie",
    "last_name": "Huniwall",
    "email": "rhuniwall1v@bloglovin.com",
    "gender": "Genderfluid",
    "ip_address": "192.64.102.166"
  }, {
    "id": 69,
    "first_name": "Benita",
    "last_name": "Aleshintsev",
    "email": "baleshintsev1w@canalblog.com",
    "gender": "Female",
    "ip_address": "12.2.42.160"
  }, {
    "id": 70,
    "first_name": "Davina",
    "last_name": "Pail",
    "email": "dpail1x@examiner.com",
    "gender": "Non-binary",
    "ip_address": "142.7.99.45"
  }, {
    "id": 71,
    "first_name": "Jenny",
    "last_name": "Rosenbaum",
    "email": "jrosenbaum1y@istockphoto.com",
    "gender": "Female",
    "ip_address": "13.57.226.207"
  }, {
    "id": 72,
    "first_name": "Barron",
    "last_name": "Purchon",
    "email": "bpurchon1z@shinystat.com",
    "gender": "Male",
    "ip_address": "46.114.110.83"
  }, {
    "id": 73,
    "first_name": "Fidel",
    "last_name": "Daelman",
    "email": "fdaelman20@bluehost.com",
    "gender": "Male",
    "ip_address": "96.5.86.15"
  }, {
    "id": 74,
    "first_name": "Krista",
    "last_name": "Delagua",
    "email": "kdelagua21@cbslocal.com",
    "gender": "Female",
    "ip_address": "19.174.211.82"
  }, {
    "id": 75,
    "first_name": "Zaria",
    "last_name": "Treacher",
    "email": "ztreacher22@usgs.gov",
    "gender": "Female",
    "ip_address": "33.68.121.213"
  }, {
    "id": 76,
    "first_name": "Curry",
    "last_name": "Goscar",
    "email": "cgoscar23@plala.or.jp",
    "gender": "Male",
    "ip_address": "122.190.122.84"
  }, {
    "id": 77,
    "first_name": "Jessamine",
    "last_name": "Learoyd",
    "email": "jlearoyd24@wunderground.com",
    "gender": "Female",
    "ip_address": "30.15.22.233"
  }, {
    "id": 78,
    "first_name": "Chad",
    "last_name": "Kiezler",
    "email": "ckiezler25@uiuc.edu",
    "gender": "Male",
    "ip_address": "76.2.80.7"
  }, {
    "id": 79,
    "first_name": "Jerry",
    "last_name": "Lockart",
    "email": "jlockart26@clickbank.net",
    "gender": "Female",
    "ip_address": "49.98.224.126"
  }, {
    "id": 80,
    "first_name": "Janine",
    "last_name": "Colley",
    "email": "jcolley27@icio.us",
    "gender": "Female",
    "ip_address": "153.1.124.227"
  }, {
    "id": 81,
    "first_name": "Persis",
    "last_name": "Garcia",
    "email": "pgarcia28@mapy.cz",
    "gender": "Female",
    "ip_address": "92.63.86.67"
  }, {
    "id": 82,
    "first_name": "Andonis",
    "last_name": "Szwarc",
    "email": "aszwarc29@theatlantic.com",
    "gender": "Male",
    "ip_address": "143.51.120.49"
  }, {
    "id": 83,
    "first_name": "Marge",
    "last_name": "Sonley",
    "email": "msonley2a@yolasite.com",
    "gender": "Female",
    "ip_address": "26.25.139.113"
  }, {
    "id": 84,
    "first_name": "Felike",
    "last_name": "Fridd",
    "email": "ffridd2b@livejournal.com",
    "gender": "Male",
    "ip_address": "99.137.91.50"
  }, {
    "id": 85,
    "first_name": "Tobiah",
    "last_name": "Cramb",
    "email": "tcramb2c@drupal.org",
    "gender": "Male",
    "ip_address": "97.9.14.139"
  }, {
    "id": 86,
    "first_name": "Caril",
    "last_name": "Flintuff",
    "email": "cflintuff2d@craigslist.org",
    "gender": "Female",
    "ip_address": "48.16.172.67"
  }, {
    "id": 87,
    "first_name": "Jarrett",
    "last_name": "Baglin",
    "email": "jbaglin2e@naver.com",
    "gender": "Male",
    "ip_address": "79.163.38.105"
  }, {
    "id": 88,
    "first_name": "Ashlan",
    "last_name": "Stobart",
    "email": "astobart2f@cdbaby.com",
    "gender": "Female",
    "ip_address": "247.119.67.113"
  }, {
    "id": 89,
    "first_name": "Frannie",
    "last_name": "O' Finan",
    "email": "fofinan2g@tumblr.com",
    "gender": "Male",
    "ip_address": "234.75.59.11"
  }, {
    "id": 90,
    "first_name": "Dinnie",
    "last_name": "Whithalgh",
    "email": "dwhithalgh2h@goodreads.com",
    "gender": "Genderqueer",
    "ip_address": "216.9.102.162"
  }, {
    "id": 91,
    "first_name": "Julianna",
    "last_name": "Eck",
    "email": "jeck2i@topsy.com",
    "gender": "Genderfluid",
    "ip_address": "222.94.7.241"
  }, {
    "id": 92,
    "first_name": "Jorry",
    "last_name": "Passo",
    "email": "jpasso2j@dyndns.org",
    "gender": "Female",
    "ip_address": "101.74.219.175"
  }, {
    "id": 93,
    "first_name": "Lorry",
    "last_name": "Tiddy",
    "email": "ltiddy2k@ca.gov",
    "gender": "Male",
    "ip_address": "76.53.45.214"
  }, {
    "id": 94,
    "first_name": "Gilly",
    "last_name": "Luttgert",
    "email": "gluttgert2l@list-manage.com",
    "gender": "Female",
    "ip_address": "199.201.161.242"
  }, {
    "id": 95,
    "first_name": "Vincents",
    "last_name": "Frenchum",
    "email": "vfrenchum2m@omniture.com",
    "gender": "Male",
    "ip_address": "234.63.46.238"
  }, {
    "id": 96,
    "first_name": "Ode",
    "last_name": "Roizn",
    "email": "oroizn2n@timesonline.co.uk",
    "gender": "Male",
    "ip_address": "158.61.64.31"
  }, {
    "id": 97,
    "first_name": "Franchot",
    "last_name": "Mucklo",
    "email": "fmucklo2o@umn.edu",
    "gender": "Male",
    "ip_address": "74.149.194.40"
  }, {
    "id": 98,
    "first_name": "Kara-lynn",
    "last_name": "Ransfield",
    "email": "kransfield2p@dailymotion.com",
    "gender": "Female",
    "ip_address": "101.1.5.32"
  }, {
    "id": 99,
    "first_name": "Mamie",
    "last_name": "Rillatt",
    "email": "mrillatt2q@indiatimes.com",
    "gender": "Female",
    "ip_address": "254.110.189.74"
  }, {
    "id": 100,
    "first_name": "Melloney",
    "last_name": "Bittleson",
    "email": "mbittleson2r@chronoengine.com",
    "gender": "Genderqueer",
    "ip_address": "110.40.156.9"
  }]


const MUITable = () => {
  return (
    <TableContainer component={Paper} sx={{maxHeight: '500px'}}>
        <Table arial-label='table' stickyHeader>
            <TableHead> 
                <TableRow >
                    <TableCell >ID</TableCell>
                    <TableCell>Firstname</TableCell>
                    <TableCell>Lastname</TableCell>
                    <TableCell align="center">Email</TableCell>
                    <TableCell> </TableCell>
                </TableRow>
            </TableHead>
            <TableBody>
                {
                    tableData.map( (data) =>(
                        <TableRow key={data.id} 
                                  sx={{'$:last-child td,{$:last-child th' : {border: 0}}}>
                            <TableCell>{data.id}</TableCell>
                            <TableCell>{data.first_name}</TableCell>
                            <TableCell>{data.last_name}</TableCell>
                            <TableCell align="center">{data.email}</TableCell>
                            <TableCell align="center"> 
                                <Tooltip title='Delete' 
                                    placement="bottom" 
                                    arrow 
                                    enterDelay={100} leaveDelay={200}
                                    color="error"
                                    
                                    
                                    >
                                    <IconButton disableRipple>
                                        <DeleteIcon/>
                                    </IconButton>
                                </Tooltip>
                            </TableCell>
                       

                        </TableRow>
                    ))
                }
            </TableBody>
        </Table>
    </TableContainer>
  )
}

export default MUITable
